In [43]:
import pandas as pd
import numpy as np
import random
import math
from numpy import array
from scipy.spatial import distance
from sklearn.preprocessing import StandardScaler
from itertools import cycle, islice
import matplotlib.pyplot as plt
from pandas.tools.plotting import parallel_coordinates

%matplotlib inline

In [44]:
#reading file
data = pd.read_csv('./weather/daily_weather.csv', low_memory = False)

In [45]:
#getting rows and colums
data.shape

(1095, 11)

In [46]:
sampled_df = data[(data['number'] % 10) == 0]
sampled_df.shape

(110, 11)

In [47]:
sampled_df.describe().transpose()

count        mean          std         min  \
number                  110.0  545.000000   318.982758    0.000000   
air_pressure_9am        110.0  918.603393     3.071110  910.340000   
air_temp_9am            109.0   67.405654    11.805028   42.134000   
avg_wind_direction_9am  110.0  150.047497    67.672077   28.900000   
avg_wind_speed_9am      109.0    5.326938     4.393845    0.917145   
max_wind_direction_9am  110.0  156.467570    64.538380   38.300000   
max_wind_speed_9am      110.0    6.901317     5.440086    1.342164   
rain_accumulation_9am   109.0    0.253258     1.771543    0.000000   
rain_duration_9am       110.0  262.576396  1357.633712    0.000000   
relative_humidity_9am   110.0   31.419408    23.423758    6.929473   
relative_humidity_3pm   110.0   33.765091    21.342965    9.130000   

                               25%         50%         75%           max  
number                  272.500000  545.000000  817.500000   1090.000000  
air_pressure_9am        916.825000  918.120000  920.982489    925.960000  
air_temp_9am             58.946000   68.253823   75.664048     98.906000  
avg_wind_direction_9am   73.044125  171.100000  192.275000    292.800000  
avg_wind_speed_9am        2.234508    3.511996    7.695571     21.314179  
max_wind_direction_9am   85.975194  186.900000  201.775000    295.400000  
max_wind_speed_9am        3.079926    4.697574    9.870498     25.605325  
rain_accumulation_9am     0.000000    0.000000    0.000000     17.616000  
rain_duration_9am         0.000000    0.000000    0.000000  10560.000000  
relative_humidity_9am    16.444170   22.220080   35.845000     90.580000  
relative_humidity_3pm    18.294021   23.487313   49.635000     91.680000

In [48]:
sampled_df[sampled_df['rain_accumulation_9am'] == 0].shape

(97, 11)

In [49]:
sampled_df[sampled_df['rain_duration_9am'] == 0].shape

(95, 11)

In [50]:
del sampled_df['rain_accumulation_9am']
del sampled_df['rain_duration_9am']

In [51]:
rows_before = sampled_df.shape[0]
sampled_df = sampled_df.dropna()
rows_after = sampled_df.shape[0]

In [52]:
rows_before - rows_after

2

In [53]:
sampled_df.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'relative_humidity_9am', 'relative_humidity_3pm'],
      dtype='object')

In [54]:
features = ['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am', 'avg_wind_speed_9am', 'max_wind_direction_9am', 
        'max_wind_speed_9am','relative_humidity_9am','relative_humidity_3pm']

In [55]:
select_df = sampled_df[features]

In [56]:
select_df.columns

Index(['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'relative_humidity_9am', 'relative_humidity_3pm'],
      dtype='object')

In [57]:
X = StandardScaler().fit_transform(select_df)
X

array([[ -2.06990280e-01,   6.20895578e-01,   1.78768779e+00,
         -7.51556725e-01,   2.15310082e+00,  -7.45517621e-01,
          4.90775465e-01,   1.32853378e-01],
       [  3.24081589e-01,   8.10765721e-01,  -1.16464871e+00,
         -3.52610919e-01,  -1.08897445e+00,  -3.91309771e-01,
         -3.95017082e-01,  -6.15136825e-02],
       [  4.38399711e-01,  -3.96000272e-01,  -1.39731501e+00,
          1.67211710e+00,  -1.26267456e+00,   1.59966644e+00,
         -5.36938987e-01,  -9.04579150e-01],
       [  2.23879350e-01,   2.01790760e+00,  -7.84747055e-01,
         -6.49262929e-01,  -9.22159711e-01,  -6.49673144e-01,
         -2.40493075e-01,   1.10185259e-01],
       [  2.07178977e-01,  -2.88319984e-01,   4.78646820e-01,
          1.23294293e+00,   4.71052240e-01,   9.17175698e-01,
          1.51693208e-01,   1.34632118e+00],
       [  1.07559839e+00,  -1.46303292e-01,   7.26024641e-01,
         -1.99170224e-01,   7.90780482e-01,  -2.87130992e-01,
         -9.05163944e-01,  -8.6

In [58]:

def Euclediandistance(x,y):
    return np.linalg.norm(x-y)



In [59]:


def Centroidscompare(p1, p2):
    if len(p1) != len(p2):
        return False
    for p1, p2 in zip(p1, p2):
        if p1[0] != p2[0] or p1[1] != p2[1]:
            return False   
    return True

In [60]:
def findCentroids(clusters):
    return [np.mean(cluster, axis=0) for cluster in clusters]


In [61]:


def Centroidscompare(p1, p2):
    if len(p1) != len(p2):
        return False
    for p1, p2 in zip(p1, p2):
        if p1[0] != p2[0] or p1[1] != p2[1]:
            return False   
    return True

In [62]:
def closestCentroid(point, centroids):
    min_distance = float('inf')
    clusterPoint = None
    for i,centroid in enumerate(centroids):
        dist = Euclediandistance(point, centroid)
        if dist < min_distance:
            min_distance = dist
            clusterPoint = i
    return clusterPoint


def MyKMeans(k, centroids, points):
    clusters = [[] for _ in range(k)]
    for point in points:
        clusters[closestCentroid(point, centroids)].append(point)
        
    new_centroids = findCentroids(clusters)
    
    if not Centroidscompare(centroids, new_centroids):
        clusters = MyKMeans(k, new_centroids, points)
        
    return array(new_centroids)

In [63]:
k = 12
centroids = X[:k]               #picking the first k points as centroids
centersMyKmeans = MyKMeans(k, centroids, X)
centersMyKmeans

array([[-0.22452567,  0.32374109,  1.19206679, -0.79503159,  1.61520052,
        -0.77572947,  0.20686481,  0.77274543],
       [ 0.14326617,  0.14401448, -1.20416605, -0.31674225, -1.25716181,
        -0.3363737 , -0.24656487, -0.07179055],
       [ 1.12453144, -0.65925357, -1.42048948,  1.70744402, -1.31967372,
         1.74865826, -0.59689587, -0.82841431],
       [-0.71969174,  2.35210993, -0.07574455, -0.69529514, -1.25347231,
        -0.65175672, -0.54801761, -0.0265469 ],
       [-0.38427117, -0.84308753,  0.30885774,  1.02638814,  0.42138802,
         0.96173216,  0.91390003,  1.39625782],
       [ 1.07780351,  0.02072037,  0.76588761, -0.32527436,  0.73095976,
        -0.31071334, -0.47934783, -0.69735477],
       [-0.51099941,  0.961427  ,  0.97236025, -0.76111893,  0.58681406,
        -0.77928306, -0.54146815, -0.56608386],
       [-0.71973994,  1.0187796 , -0.5801665 , -0.67752134, -0.4284518 ,
        -0.65562382, -0.63249869, -0.56219449],
       [-0.45553003, -0.14681224

In [64]:
#using scikit libraries

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=12)
model = kmeans.fit(X)
centers = model.cluster_centers_
centers

array([[-0.40333707,  0.85139152,  1.45159334, -0.78505811,  1.1907632 ,
        -0.78923747, -0.26752053, -0.33540708],
       [ 1.14190092, -0.77927532, -1.40523592,  1.23040605, -1.28894314,
         1.29452413, -0.55173902, -0.75994258],
       [ 0.71864504,  0.06388589, -0.33299388, -0.51922275, -0.80196607,
        -0.4765576 , -0.64969511, -0.7061737 ],
       [-1.16191762, -1.5542753 ,  0.49042672, -0.14393157,  0.56094685,
        -0.13127954,  2.52000214,  1.76114775],
       [ 0.06928161, -0.80213814,  0.2373693 ,  1.15768392,  0.33115734,
         1.07374152,  0.79428922,  1.75241812],
       [-0.33862934,  0.74635972, -1.1052807 , -0.32658688, -1.2065346 ,
        -0.32950928, -0.4852712 , -0.31197632],
       [-0.85867596,  0.73478336,  0.23912226, -0.67199488,  0.43037828,
        -0.65569236,  0.42640255,  0.95480043],
       [-0.96042427,  1.20493376,  0.33509844, -0.67937976,  0.16377817,
        -0.69097851, -0.49773971, -0.47130581],
       [ 1.08284469, -0.37120135

In [65]:
difference = ((centers-centersMyKmeans)**2).sum()
difference

128.33076116373184